replicaCount: 1

image:
  repository: ghcr.io/bebusl/flipnote-group
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

existingSecret: "group-service-secret"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8084
  grpcPort: 9094

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8084
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8084
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi

env: []

configMap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

externalSecret:
  enabled: false
  refreshInterval: "1h"
  secretStoreName: "vault-backend"
  secretStoreKind: "ClusterSecretStore"
  remoteKey: "secret/data/flipnote/group-service"
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteProperty: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteProperty: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteProperty: SPRING_DATASOURCE_PASSWORD
    - secretKey: GRPC_IMAGE_URL
      remoteProperty: GRPC_IMAGE_URL
    - secretKey: GRPC_USER_URL
      remoteProperty: GRPC_USER_URL
    - secretKey: RESEND_API_KEY
      remoteProperty: RESEND_API_KEY
    - secretKey: RESEND_FROM_EMAIL
      remoteProperty: RESEND_FROM_EMAIL
    - secretKey: APP_CLIENT_URL
      remoteProperty: APP_CLIENT_URL
    - secretKey: SWAGGER_SERVER_URL
      remoteProperty: SWAGGER_SERVER_URL
    - secretKey: RABBITMQ_HOST
      remoteProperty: RABBITMQ_HOST
    - secretKey: RABBITMQ_PORT
      remoteProperty: RABBITMQ_PORT
    - secretKey: RABBITMQ_USERNAME
      remoteProperty: RABBITMQ_USERNAME
    - secretKey: RABBITMQ_PASSWORD
      remoteProperty: RABBITMQ_PASSWORD
